### PR TITLE
TokenPainter classes public and setTokenPainter method for changing token painter

### PR DESCRIPTION
**Pull request by IonAgorria**
I would like to implement a custom TokenPainter but classes and variable are package/private only...

### CODE REVIEW

**Comment by bobbylight** [comment]
Out of curiosity, may I ask why you need to implement your own TokenPainter?

**Comment by IonAgorria** [comment]
I need to change per character background and I thought that was the best way

**Comment by IonAgorria** [comment]
This will be merged?

**Comment by RobertBColton** [comment]
I was also interested in painting the visible whitespace myself. I wanted to make the tab characters look like the ones in Eclipse IDE as the straight arrow line is too much visual clutter.

**Comment by bobbylight** [comment]
Closing as this will (finally) be addressed in #534.

**Pull request closed without merging**
