### PR TITLE
Issue457: Fractional Scaling on Windows

### PR DESCRIPTION
**Pull request by ptorngren**
Add support for FPAPI: Add new class SwingUtils with methods for leveraging the FPAPI 

Modify concerned classes and methods to call SwingUtils and use Rectangle2D and float/double variables instead of Rectangle and integers: 
- DefaultTokenPainter.paintBackground() 
- RSyntaxUtilities.getLineWidthUpTo()
- SyntaxView: tabBase, tabSize, clipStart, clipEnd, .calculateLongestLine(), lineToRect(), damageLineRange(), modelToView(), nextTabStop(), paint()
- Token.listOffsetToView() 
- TokenImpl: getListOffset(), getWidthUpTo(), listOffsetToView()
- VisibleWhitespaceTokenPainter()
- WrappedSyntaxView.modelToView()

Layout/painter changes:
- SyntaxViiew.nextTabStop(): Add offset for tabs to avoid losing tabs that occur on the same pixel as the preceding character end
- ConfigurableCaret: use Rectangle2D and floats/doubles, primarily to avoid double lines on thick vertical line style
- Add RSyntaxTextArea.onGraphicsChange() to let owner refresh font metrics when graphic properties change
- DefaultTokenPainter: Fix tab lines by offsetting the line location slightly
- SwingUtils.drawChars(): Use TextLayout for very long lines or containing complex characters (inspired by SwingUtilities2)

Adapt to Java 11: Replace calls to deprecated elements with corresponding elements for Java 9 or later
Rectangles and bounds: 
- add SwingUtils.getBounds() to wrap calls to modelToView2D(pos).getBounds() in a null-safe way
- replace calls to JTextComponent.modelToView(int pos) with calls to SwingUtils.getBounds(JTextComponent c, int pos) 
- replace calls to JTextComponent.viewToModel(Point p) with calls to JTextComponent.viewToModel2D(Point2D p) 

Events: 
- replace calls to InputEvent.getModifiers() with calls to MouseEvent.getModifiersEx() 
- replace calls to Toolkit.getMenuShortcutKeyMask() Toolkit.getMenuShortcutKeyMaskEx() 
- replace references to Event.META_MASK with InputEvent.META_DOWN_MASK 
- replace references to Event.CTRL_MASK with InputEvent.CTRL_DOWN_MASK 
- replace references to MouseEvent.BUTTON1_MASK with MouseEvent.BUTTON1_DOWN_MASK Not modified: 
- SyntaxScheme calls deprecated XMLReaderFactory.createXMLReader() which should be replaced with SaxParserFactory

Also modified the Demo Root Pane:
- add a text example
- show a larger screen centered on monitor
- add a font selector
- add menu option to make whitespace visible

### CODE REVIEW

**Comment by bobbylight** [comment]
@ptorngren - I'm *finally* looking at this, thank you! I started down this path myself but it's a very large task and I'm duplicating effort here.

Can you rebase this PR against the `java-11` branch? All it does so far is update the build to use Java 11. After that, if things look good, can we squash and merge?

My plan is then to release a 4.0.0-SNAPSHOT release to Sonatype while I do a bit more code modernization for Java 11, bump checkstyle, etc.

**Comment by ptorngren** [comment]
Hi,

Will do asap, but not immediately since we’re shipping a major release 
“as we speak”. Hope to get around to this in a matter of weeks.

Hälsningar/Regards

Peer Törngren
p2r software AB (p2r.se)


------ Original Message ------
From "bobbylight" ***@***.***>
To "bobbylight/RSyntaxTextArea" ***@***.***>
Cc "Peer Törngren" ***@***.***>; "Mention" 
***@***.***>
Date 2024-11-19 13:57:17
Subject Re: [bobbylight/RSyntaxTextArea] Issue457: Fractional Scaling on 
Windows (PR #524)

**Comment by ptorngren** [comment]
Hi

Just rebased from the Java 11 branch to the best of my ability. There 
were quite a few merge conflicts to handle manually, and since I haven’t 
run this other than trying to start the demo app on macOS without any 
fractional scaling, I cannot guarantee that there are no errors.

Also, there are a few warnings about deprecated methods that I haven’t 
addressed.

Still, I hope this helps and that we can expect to update to version 4 
soon!

Regards

Peer Törngren


------ Original Message ------
From "bobbylight" ***@***.***>
To "bobbylight/RSyntaxTextArea" ***@***.***>
Cc "Peer Törngren" ***@***.***>; "Mention" 
***@***.***>
Date 2024-11-19 13:57:17
Subject Re: [bobbylight/RSyntaxTextArea] Issue457: Fractional Scaling on 
Windows (PR #524)

**Comment by bobbylight** [comment]
Thanks for the PR!

**Comment by bobbylight** [comment]
BTW, this is still on the `java-11` branch. I'ma do a bit more tidying up, and test on Windows (only have access to Windows 10 but can do some basic testing with Java 11, 17 and 21).

Folks interested in trying this out can use the `4.0.0-SNAPSHOT` from Sonatype:

```gradle
repositories {
  mavenCentral()
  maven {
    url 'https://oss.sonatype.org/content/repositories/snapshots'
  }
}
```

Note that `3.5.3` was just relesed as the latest version supporting Java 8, and as needed I'll release a `3.5.4`, etc., and continue to rebase the Java 11/`4.0.0` stuff on top of it, until it's ready to go.

**Pull request merged**
