### PR TITLE
Fix ErrorStrip's Marker Positions when LineCount less than Possible LineCount

### LINKED ISSUE #380: ErrorStrip's Markers Position is wrong when LineCount << VisualRect
Greetings.

Currently, the Markers are shown at the wrong position when there are less Lines than Lines possible defined by the Visual Rectangle of the Scroll Pane. The picture below illustrates that well. As you can see, the Line 2 Marker is somewhere in the middle, while the Error Marker for Line 3 is shown at the bottom.

The root cause is calculating the fraction based on Actual LineCount instead of Possible Line Count (defined by the Visual Rectangle).

image

### PR DESCRIPTION
**Pull request by manticore-projects**
Calculate the Position based on the Possible Line Count defined by the Visual Rectangle. Fixes #380.

Using the improvement, it would look like this:
image

Also works for Actual Line Count greater than the Possible Line Count, although we would like to factor in the offset from scrolling eventually.

image

### CODE REVIEW

**Comment by manticore-projects** [comment]
You can try the correction/PR online: http://217.160.215.75:8080/jsqlformatter/demo.html
Including the extended Syntax highlighting for CASE/WITH.

https://user-images.githubusercontent.com/18080123/117129424-d8f60b80-adc8-11eb-94cc-b6383f7ed73e.mp4

**Comment by bobbylight** [comment]
Thanks @manticore-projects.  I see that this PR included the SQLTokenMaker PR as well, which is causing a merge conflict as I've already merged that one.  Can you redo this to omit the SQLTokenMaker changes?

**Comment by manticore-projects** [comment]
Sorry! Should be fine now.

**Comment by bobbylight** [comment]
GitHub still isn't happy and won't let me rebase and merge, likely because I reformatted your flex changes (tabs vs. spaces, etc.).  Perhaps a commit removing the TokenMaker.(flex|java) files on this branch will fix things?

**Comment by manticore-projects** [comment]
Bobby, apologies for taking so long.

> GitHub still isn't happy and won't let me rebase and merge,
Coming from Mercurial, I actually struggle to understand how Git works. To me it seems to do a poor job with branching and merging (compared to Mercurial), but maybe a keep doing things wrong.

I have hard reset to your latest commit and re-implemented the ErrorStrip changes only line by line and forced pushed into my repo. If this did not work, then I would not know what else to do. Please bear with me.

**Comment by bobbylight** [comment]
Looks like the issue is that the ErrorStrip work was done on top of the other PR you made to add new SQL keywords (which has been merged).  I think the best bet is to abandon this PR and create a new one with just a commit for the `ErrorStrip` changes. That will avoid the chance of any issues with the SQL keyword commit (it was merged but stuff like spacing was changed, removing it will preserve a clean commit history and avoid changes that are just whitespace).

**Comment by bobbylight** [comment]
Fixed by the cherry-pick from this work in #397.  Thanks again @manticore-projects!

**Pull request closed without merging**
