### PR TITLE
Add search wrap capability

### PR DESCRIPTION
**Pull request by giles7777**
I added a SearchContext capability to wrap around the direction of searching.  A separate pull request for the rsta project contains the user interface changes.

### CODE REVIEW

**Comment by paul-griffith** [comment]
@bobbylight Are you okay with implementing this? I can work at rebasing/redoing this & https://github.com/bobbylight/RSTAUI/pull/14, but won't worry about it if it's not something you want to implement.

**Comment by giles7777** [comment]
I'm not deeply familiar with the code so if you wanted to just use my
commit as an example I'd be fine with that.  It's been a long time since I
looked at it.

**Comment by bobbylight** [comment]
Thanks guys, I've been meaning to look at this PR but have been busy with mundane tasks like implementing proper Maven dependency support between all the RSTA projects.  I'm happy for either of you to PR this.  @paul-griffith I'll take a look at your most recent PR based off of @giles7777's.

**Comment by bobbylight** [comment]
Closing since this PR was superseded by #329.

**Pull request closed without merging**
