### PR TITLE
Gutter's LineNumberList now highlights current line number 

### PR DESCRIPTION
**Pull request by omegaui**
```
org.fife.ui.rtextarea.LineNumberList
```
Now paints the current line number with a different color.

Screenshot from 2021-12-31 10-04-37

### CODE REVIEW

**Comment by omegaui** [comment]
This is a simple add-on.
But it was something that an **editor must have**!
😁

**Review by bobbylight — COMMENTED** [review]
Thanks for the PR!  There are a couple of changes I'd like before merging this.  Could you please:

* Remove the empty line added to README.md
* Make `LineNumberList.currentLineNumberColor` default to `numberColor` if not defined
* Cache the value of `textArea.getCaretLineNumber()` in `paintComponent()` so it isn't called repeatedly in the loop
* Also update `paintWrappedLineNumbers()` with similar changes to `paintComponent()`
* Squash and rebase

If you make those changes, I'll also update [Theme](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/Theme.java) and friends so the default themes take advantage of this feature (unless you want to do that yourself too :)).

**Comment by omegaui** [comment]
Just Doing So!

**Comment by omegaui** [comment]
Suffering with **checkstyle** :(

**Comment by omegaui** [comment]
@bobbylight 
Should I ignore the checkstyle errors.

All the errors just say "line has trailing space" and only occur in LineNumberList

**Comment by omegaui** [comment]
@bobbylight 
Done!
You can simply squash and merge now!

>If you make those changes, I'll also update Theme and friends so the default themes take advantage of this feature (unless you want to do that yourself too :)).

It can be done better, if done by you cause' I need to first understand how the **Theme** API is working which will take ages for me (🤧) to understand.

**Comment by bobbylight** [comment]
Sounds good, I'll take a look at updating the `Theme` API to accomodate this property one this is merged.

I hate to be that guy, but can you do another commit to remove the whitespace/newline changes?  e.g. I don't think `README.md` has changed, and all the documentation comments losing the whitespace asterisk indentation, as well as a few other indentation changes.  I'm a stickler for preserving history 😛

**Comment by bobbylight** [comment]
Thanks for the PR!

**Pull request merged**
