### PR TITLE
Finnish translation added, French and Ukrainian translation updated

### PR DESCRIPTION
**Pull request by kosivantsov**
RSyntaxTextArea is used in [OmegaT](https://github.com/omegat-org/omegat) in its script editor. I created several team translation projects for third-party stuff used in OmegaT, RsyntaxTextArea strings included, and here are files for 3 languages (Finnish, French, Ukrainian). More is pretty likely to come soon.

### CODE REVIEW

**Comment by kosivantsov** [comment]
Translation is provided by professional translators into their respective language (Ukrainian is mine, I happen to translate into Ukrainian for living). I manage localization efforts for OmegaT. If more translations are to arrive, they'll be done by people who localized OmegaT, it's documentation and website in their languages.

**Comment by bobbylight** [comment]
@kosivantsov I'm so happy new life is being breathed into the translations!  I just merged the Dutch updates.  I'm happy to take these as well, but I had a question about some of the French files being replaced with empty files?  Was this an oversight?

**Comment by bobbylight** [comment]
Nevermind - I see now this is just GitHub's confusing way of saying "this file was only chmod'd, its contents didn't change."

Thanks again!  I hope to cut a new release that includes these localization updates soon.

**Comment by kosivantsov** [comment]
There'll be about half a dozen new translations added. Could you wait till May 14 with the release? I'll PR those translations, and you could roll out the release on weekend

**Comment by bobbylight** [comment]
Sounds good.  Yeah the speed at which I'm working on RSTA and friends lately, it'll be at least May 14.  I'll publish SNAPSHOT releases to Sonatype with the changes though if I get bogged down for whatever reason.

**Pull request merged**
